local P,R,C,LP,U=game:GetService("Players"),game:GetService("RunService"),workspace.CurrentCamera,game:GetService("Players").LocalPlayer,game:GetService("UserInputService")
local _G,pE,sA,tk={Aim=true,At=true,Ds=true,Sm=1,F=150,Wb=true,V=true,Ch=true,Sk=true,Tm=true,Sp=false,Yw=true,Up=false,Off=180,Spd=50},{},0,0
local G=Instance.new("ScreenGui",LP.PlayerGui)G.IgnoreGuiInset=true local M=Instance.new("Frame",G)M.Size,M.Position,M.BackgroundColor3=UDim2.new(0,180,0,180),UDim2.new(0.5,-90,0.5,-90),Color3.new(0,0,0)Instance.new("UICorner",M)
local function L()local l=Instance.new("Frame",G)l.BackgroundColor3,l.BorderSizePixel,l.Visible,l.ZIndex=Color3.new(1,1,1),0,false,99 return l end
local function draw(l,p1,p2)local d=(p1-p2).Magnitude l.Size,l.Position,l.Rotation,l.Visible=UDim2.new(0,d,0,1),UDim2.new(0,(p1.X+p2.X)/2-d/2,0,(p1.Y+p2.Y)/2),math.deg(math.atan2(p2.Y-p1.Y,p2.X-p1.X)),true end
local function Btn(n,v,y)local b=Instance.new("TextButton",M)b.Size,b.Position,b.Text,b.BackgroundColor3,b.TextColor3=UDim2.new(0.9,0,0,25),UDim2.new(0.05,0,0,y),n,_G[v] and Color3.new(0,0.5,1) or Color3.new(0.2,0.2,0.2),Color3.new(1,1,1)b.MouseButton1Click:Connect(function()_G[v]=not _G[v]b.BackgroundColor3=_G[v] and Color3.new(0,0.5,1) or Color3.new(0.2,0.2,0.2)end)end
Btn("AIM","Aim",10)Btn("ESP","V",40)Btn("DESYNC","Ds",70)Btn("YAW","Yw",100)Btn("UP-DOWN","Up",130)
local d,ds,sp M.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then d,ds,sp=true,i.Position,M.Position end end)
U.InputChanged:Connect(function(i)if d and (i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch)then local dl=i.Position-ds M.Position=UDim2.new(sp.X.Scale,sp.X.Offset+dl.X,sp.Y.Scale,sp.Y.Offset+dl.Y)end end)U.InputEnded:Connect(function()d=false end)
local function getB(c)for _,n in{"Head","Torso","Left Arm","Right Arm"}do local p=c:FindFirstChild(n)if p then local r=Ray.new(C.CFrame.Position,(p.Position-C.CFrame.Position).Unit*500)local h=workspace:FindPartOnRayWithIgnoreList(r,{LP.Character,c})if not h or(_G.Wb and(h.Transparency>0.5 or h.Material==Enum.Material.Wood))then return p end end end end
R.RenderStepped:Connect(function()local t,m,ct=nil,_G.F,Vector2.new(C.ViewportSize.X/2,C.ViewportSize.Y/2)tk=(tk+1)%2 local ch=LP.Character if ch and ch:FindFirstChild("HumanoidRootPart")then local hr,rj=ch.HumanoidRootPart,ch.HumanoidRootPart:FindFirstChild("RootJoint")if _G.Ds and tk==0 then hr.CFrame=hr.CFrame*CFrame.new(0,0,0.05)end if rj then local x=_G.Up and 90 or-90 if _G.Yw then rj.C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(x),0,math.rad(_G.Off+180))else rj.C0=CFrame.new(0,0,0)*CFrame.Angles(math.rad(-90),3.14,0)end end end
for _,p in pairs(P:GetPlayers())do if p~=LP and p.Character and p.Character:FindFirstChild("Torso")then if not pE[p] then pE[p]={h=Instance.new("Highlight",G),s={ht=L(),la=L(),ra=L(),ll=L(),rl=L()}}end local e,c=pE[p],p.Character e.h.Enabled,e.h.Adornee,e.h.FillColor=_G.V and _G.Ch,c,Color3.new(0,1,0.5)local ps,vis=C:WorldToViewportPoint(c.Torso.Position)for _,s in pairs(e.s)do s.Visible=false end if vis and _G.V then if _G.Sk then local function g(pt)local o=c:FindFirstChild(pt)if o then local oP,oV=C:WorldToViewportPoint(o.Position)if oV then return Vector2.new(oP.X,oP.Y)end end end local h,t0,la,ra,ll,rl=g("Head"),g("Torso"),g("Left Arm"),g("Right Arm"),g("Left Leg"),g("Right Leg")if h and t0 and la and ra and ll and rl then draw(e.s.ht,h,t0)draw(e.s.la,t0,la)draw(e.s.ra,t0,ra)draw(e.s.ll,t0,ll)draw(e.s.rl,t0,rl)end end if(Vector2.new(ps.X,ps.Y)-ct).Magnitude<m then local b=getB(c)if b then t,m=b,(Vector2.new(ps.X,ps.Y)-ct).Magnitude end end end end end
if _G.Aim and t then C.CFrame=C.CFrame:Lerp(CFrame.lookAt(C.CFrame.Position,t.Position),1/_G.Sm)if _G.At then local r=Ray.new(C.CFrame.Position,C.CFrame.LookVector*999)local h=workspace:FindPartOnRayWithIgnoreList(r,{LP.Character})if h and h:IsDescendantOf(t.Parent)then mouse1press()task.wait()mouse1release()end end end end)
